In [2]:
import pandas as pd
import numpy as np

In [3]:
# read data from .tsv file and skp any bad lines in the file
data = pd.read_csv('amazon_reviews_us_Electronics_v1_00.tsv', sep='\t', error_bad_lines=False)
# print data records
data.head()

C:\Users\Aditi\AppData\Local\Temp\ipykernel_3544\4223777463.py:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv('amazon_reviews_us_Electronics_v1_00.tsv', sep='\t', error_bad_lines=False)
Skipping line 42306: expected 15 fields, saw 22
Skipping line 61136: expected 15 fields, saw 22
Skipping line 64592: expected 15 fields, saw 22

Skipping line 73268: expected 15 fields, saw 22
Skipping line 80720: expected 15 fields, saw 22
Skipping line 120624: expected 15 fields, saw 22
Skipping line 121776: expected 15 fields, saw 22

Skipping line 154351: expected 15 fields, saw 22
Skipping line 155937: expected 15 fields, saw 22

Skipping line 203615: expected 15 fields, saw 22
Skipping line 208061: expected 15 fields, saw 22
Skipping line 212638: expected 15 fields, saw 22
Skipping line 219390: expected 15 fields, saw 22
Skipping line 235195: expected 15 fields, saw 22

Skipping line 284570: expected 15 fields, saw 22
Skipping line 297246: expected 15 fields, saw 22
Skipping line 326901: expected 15 fields, saw 22

Skipping line 344609: expected 15 fields, saw 22
Skipping line 347706: expected 15 fields, saw 22
Skipping line 348978: expected 15 fields, saw 22
Skipping line 349036: expected 15 fields, saw 22
Skipping line 377234: expected 15 fields, saw 22

Skipping line 402960: expected 15 fields, saw 22

Skipping line 525406: expected 15 fields, saw 22
Skipping line 535885: expected 15 fields, saw 22
Skipping line 558276: expected 15 fields, saw 22

Skipping line 604498: expected 15 fields, saw 22
Skipping line 652606: expected 15 fields, saw 22

Skipping line 656793: expected 15 fields, saw 22
Skipping line 686204: expected 15 fields, saw 22
Skipping line 709412: expected 15 fields, saw 22
Skipping line 712042: expected 15 fields, saw 22

Skipping line 733264: expected 15 fields, saw 22
Skipping line 770653: expected 15 fields, saw 22
Skipping line 781551: expected 15 fields, saw 22

Skipping line 791527: expected 15 fields, saw 22
Skipping line 798042: expected 15 fields, saw 22
Skipping line 807385: expected 15 fields, saw 22
Skipping line 810615: expected 15 fields, saw 22
Skipping line 844532: expected 15 fields, saw 22
Skipping line 846206: expected 15 fields, saw 22
Skipping line 847697: expected 15 fields, saw 22
Skipping line 848202: expected 15 fields, saw 22

Skipping line 852145: expected 15 fields, saw 22
Skipping line 852660: expected 15 fields, saw 22
Skipping line 856127: expected 15 fields, saw 22
Skipping line 865441: expected 15 fields, saw 22
Skipping line 887198: expected 15 fields, saw 22
Skipping line 894406: expected 15 fields, saw 22
Skipping line 916051: expected 15 fields, saw 22

Skipping line 993142: expected 15 fields, saw 22
Skipping line 1011929: expected 15 fields, saw 22
Skipping line 1034946: expected 15 fields, saw 22

Skipping line 1111605: expected 15 fields, saw 22

Skipping line 1166130: expected 15 fields, saw 22

Skipping line 1180823: expected 15 fields, saw 22

Skipping line 1286843: expected 15 fields, saw 22
Skipping line 1290568: expected 15 fields, saw 22
Skipping line 1292107: expected 15 fields, saw 22

Skipping line 1310971: expected 15 fields, saw 22
Skipping line 1319111: expected 15 fields, saw 22
Skipping line 1352063: expected 15 fields, saw 22
Skipping line 1355003: expected 15 fields, saw 22
Skipping line 1357701: expected 15 fields, saw 22

Skipping line 1400165: expected 15 fields, saw 22
Skipping line 1402478: expected 15 fields, saw 22
Skipping line 1409210: expected 15 fields, saw 22
Skipping line 1436022: expected 15 fields, saw 22

Skipping line 1448705: expected 15 fields, saw 22
Skipping line 1451228: expected 15 fields, saw 22
Skipping line 1461128: expected 15 fields, saw 22
Skipping line 1464998: expected 15 fields, saw 22
Skipping line 1466419: expected 15 fields, saw 22
Skipping line 1494640: expected 15 fields, saw 22

Skipping line 1554738: expected 15 fields, saw 22
Skipping line 1557296: expected 15 fields, saw 22

Skipping line 1583737: expected 15 fields, saw 22
Skipping line 1584239: expected 15 fields, saw 22
Skipping line 1590283: expected 15 fields, saw 22
Skipping line 1634095: expected 15 fields, saw 22

Skipping line 1649977: expected 15 fields, saw 22
Skipping line 1658352: expected 15 fields, saw 22
Skipping line 1674985: expected 15 fields, saw 22
Skipping line 1686716: expected 15 fields, saw 22
Skipping line 1697922: expected 15 fields, saw 22

Skipping line 1713285: expected 15 fields, saw 22
Skipping line 1734676: expected 15 fields, saw 22
Skipping line 1738399: expected 15 fields, saw 22
Skipping line 1741814: expected 15 fields, saw 22
Skipping line 1747515: expected 15 fields, saw 22

Skipping line 1787608: expected 15 fields, saw 22
Skipping line 1794400: expected 15 fields, saw 22
Skipping line 1807723: expected 15 fields, saw 22
Skipping line 1809920: expected 15 fields, saw 22
Skipping line 1820224: expected 15 fields, saw 22
Skipping line 1830087: expected 15 fields, saw 22

Skipping line 1914778: expected 15 fields, saw 22
Skipping line 1916219: expected 15 fields, saw 22
Skipping line 1926957: expected 15 fields, saw 22
Skipping line 1935726: expected 15 fields, saw 22
Skipping line 1949568: expected 15 fields, saw 22
Skipping line 1952979: expected 15 fields, saw 22
Skipping line 1954367: expected 15 fields, saw 22
Skipping line 1963708: expected 15 fields, saw 22
Skipping line 1965034: expected 15 fields, saw 22

Skipping line 1968879: expected 15 fields, saw 22
Skipping line 1987791: expected 15 fields, saw 22
Skipping line 2002178: expected 15 fields, saw 22
Skipping line 2007411: expected 15 fields, saw 22
Skipping line 2011694: expected 15 fields, saw 22
Skipping line 2016595: expected 15 fields, saw 22
Skipping line 2021800: expected 15 fields, saw 22

Skipping line 2178514: expected 15 fields, saw 22
Skipping line 2210320: expected 15 fields, saw 22
Skipping line 2212163: expected 15 fields, saw 22

Skipping line 2254350: expected 15 fields, saw 22

Skipping line 2296430: expected 15 fields, saw 22
Skipping line 2301015: expected 15 fields, saw 22

Skipping line 2369550: expected 15 fields, saw 22
Skipping line 2372919: expected 15 fields, saw 22
Skipping line 2373511: expected 15 fields, saw 22
Skipping line 2374204: expected 15 fields, saw 22
Skipping line 2378031: expected 15 fields, saw 22
Skipping line 2387181: expected 15 fields, saw 22

Skipping line 2432561: expected 15 fields, saw 22
Skipping line 2445761: expected 15 fields, saw 22
Skipping line 2459959: expected 15 fields, saw 22
Skipping line 2470385: expected 15 fields, saw 22
Skipping line 2474790: expected 15 fields, saw 22

Skipping line 2500009: expected 15 fields, saw 22
Skipping line 2522971: expected 15 fields, saw 22
Skipping line 2523952: expected 15 fields, saw 22
Skipping line 2537329: expected 15 fields, saw 22
Skipping line 2537962: expected 15 fields, saw 22
Skipping line 2546150: expected 15 fields, saw 22

Skipping line 2611460: expected 15 fields, saw 22

Skipping line 2679125: expected 15 fields, saw 22

Skipping line 2687826: expected 15 fields, saw 22
Skipping line 2711545: expected 15 fields, saw 22
Skipping line 2737091: expected 15 fields, saw 22

Skipping line 2764733: expected 15 fields, saw 22
Skipping line 2764771: expected 15 fields, saw 22
Skipping line 2766946: expected 15 fields, saw 22
Skipping line 2795416: expected 15 fields, saw 22

Skipping line 2822371: expected 15 fields, saw 22

Skipping line 2884239: expected 15 fields, saw 22
Skipping line 2948495: expected 15 fields, saw 22

Skipping line 2978559: expected 15 fields, saw 22
Skipping line 2998169: expected 15 fields, saw 22
Skipping line 3003265: expected 15 fields, saw 22
Skipping line 3003662: expected 15 fields, saw 22

Skipping line 3035912: expected 15 fields, saw 22
Skipping line 3054746: expected 15 fields, saw 22

Skipping line 3301954: expected 15 fields, saw 22

Skipping line 3563377: expected 15 fields, saw 22

Skipping line 3952435: expected 15 fields, saw 22

Skipping line 4144878: expected 15 fields, saw 22

Skipping line 4208693: expected 15 fields, saw 22
Skipping line 4217407: expected 15 fields, saw 22

Skipping line 4382584: expected 15 fields, saw 22

Skipping line 4794835: expected 15 fields, saw 22
Skipping line 4840336: expected 15 fields, saw 22

Skipping line 5002329: expected 15 fields, saw 22
Skipping line 5012210: expected 15 fields, saw 22
Skipping line 5021546: expected 15 fields, saw 22

Skipping line 5117714: expected 15 fields, saw 22

Skipping line 5382553: expected 15 fields, saw 22
Skipping line 5405521: expected 15 fields, saw 22

Skipping line 5652268: expected 15 fields, saw 22

Skipping line 5761025: expected 15 fields, saw 22

Skipping line 6094502: expected 15 fields, saw 22

Skipping line 6875074: expected 15 fields, saw 22

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,22873041,R3ARRMDEGED8RD,B00KJWQIIC,335625766,Plemo 14-Inch Laptop Sleeve Case Waterproof Fa...,PC,5,0,0,N,Y,Pleasantly surprised,I was very surprised at the high quality of th...,2015-08-31
1,US,30088427,RQ28TSA020Y6J,B013ALA9LA,671157305,TP-Link OnHub AC1900 Wireless Wi-Fi Router,PC,5,24,31,N,N,OnHub is a pretty no nonsense type router that...,I am a Google employee and had to chance to us...,2015-08-31
2,US,20329786,RUXJRZCT6953M,B00PML2GQ8,982036237,AmazonBasics USB 3.0 A Male to A Male Cable - ...,PC,1,2,2,N,N,None of them worked. No functionality at all.,"Bought cables in 3ft, 6ft and 9ft. NONE of th...",2015-08-31
3,US,14215710,R7EO0UO6BPB71,B001NS0OZ4,576587596,Transcend P8 15-in-1 USB 2.0 Flash Memory Card...,PC,1,0,0,N,Y,just keep searching.,"nope, cheap and slow",2015-08-31
4,US,38264512,R39NJY2YJ1JFSV,B00AQMTND2,964759214,Aleratec SATA Data Cable 2.0 20in Serial ATA S...,PC,5,0,0,N,Y,Five Stars,Excellent! Great value and does the job.,2015-08-31

In [4]:
# print various attributes available in the dataset
data.columns

Index(['marketplace', 'customer_id', 'review_id', 'product_id',
       'product_parent', 'product_title', 'product_category', 'star_rating',
       'helpful_votes', 'total_votes', 'vine', 'verified_purchase',
       'review_headline', 'review_body', 'review_date'],
      dtype='object')

In [5]:
# print properties of attributes in the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6906869 entries, 0 to 6906868
Data columns (total 15 columns):
 #   Column             Dtype
---  ------             -----
 0   marketplace        object
 1   customer_id        int64
 2   review_id          object
 3   product_id         object
 4   product_parent     int64
 5   product_title      object
 6   product_category   object
 7   star_rating        int64
 8   helpful_votes      int64
 9   total_votes        int64
 10  vine               object
 11  verified_purchase  object
 12  review_headline    object
 13  review_body        object
 14  review_date        object
dtypes: int64(5), object(10)
memory usage: 790.4+ MB

In [6]:
print ("Data rows before removing null values",data.shape[0])

Data rows before removing null values 6906869

In [9]:
# check the number of null values per column
print(data.isnull().sum())

marketplace            0
customer_id            0
review_id              0
product_id             0
product_parent         0
product_title          2
product_category       0
star_rating            0
helpful_votes          0
total_votes            0
vine                   0
verified_purchase      0
review_headline       70
review_body          199
review_date           34
dtype: int64

In [10]:
# replace null values with nan
data.replace('',np.nan,inplace=True)

In [11]:
# drop nan values in the data
data.dropna(axis=0, how='any', inplace=True)

In [12]:
# check the number of null values per column replacing with nan and dropping nan
print(data.isnull().sum())

marketplace          0
customer_id          0
review_id            0
product_id           0
product_parent       0
product_title        0
product_category     0
star_rating          0
helpful_votes        0
total_votes          0
vine                 0
verified_purchase    0
review_headline      0
review_body          0
review_date          0
dtype: int64

In [13]:
print ("Data rows after removing null values",data.shape[0])

Data rows after removing null values 6906564

In [14]:
# adding a sentiment column to classify reviews as Positive or Negative

data['sentiment'] = np.where(data['star_rating'] == 5.0, 1,
                           np.where(data['star_rating'] == 4.0, 1, 0))

In [ ]:
# export the data frame to a .csv file
data.to_csv (r'amazon_electronics.csv', index = False, header=True)